### ISSUE TITLE
Where can I find "librestysignal.so" ?

### ISSUE THREAD

**Issue by rocky1001** [openresty/lua-resty-signal#5]
Hi,

When I require lua-resty-shell(which requires lua-resty-signal) in my openresty lua code,
encountered following error msg:

````
lua entry thread aborted: runtime error: could not load librestysignal.so from the following paths:
/usr/local/openresty/site/lualib/librestysignal.so
/usr/local/openresty/lualib/librestysignal.so
./librestysignal.so
/usr/local/lib/lua/5.1/librestysignal.so
/usr/local/openresty/luajit/lib/lua/5.1/librestysignal.so
/usr/local/lib/lua/5.1/librestysignal.so
````

so where can I find or make this librestysignal.so?

Thanks.

**Comment by spacewander** [comment]
You may need to run `make` to build the shared library:
https://github.com/openresty/lua-resty-signal/blob/master/Makefile#L13

**Comment by rocky1001** [comment]
worked! thank you very much!
